// Code generated by ObjectBox; DO NOT EDIT.
// Learn more about defining entities and generating this file - visit https://golang.objectbox.io/entity-annotations

package models

import (
	"errors"
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type appUser_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var AppUserBinding = appUser_EntityInfo{
	Entity: objectbox.Entity{
		Id: 2,
	},
	Uid: 3772536781229214116,
}

// AppUser_ contains type-based Property helpers to facilitate some common operations such as Queries.
var AppUser_ = struct {
	Id           *objectbox.PropertyInt64
	ExtId        *objectbox.PropertyString
	CreatedAt    *objectbox.PropertyInt64
	UpdatedAt    *objectbox.PropertyInt64
	FirstName    *objectbox.PropertyString
	LastName     *objectbox.PropertyString
	Email        *objectbox.PropertyString
	Phone        *objectbox.PropertyString
	Token        *objectbox.PropertyString
	IsBlocked    *objectbox.PropertyBool
	IsFarm       *objectbox.PropertyBool
	IsGasStation *objectbox.PropertyBool
	IsHarvesting *objectbox.PropertyBool
	IsPayDesk    *objectbox.PropertyBool
	IsWarehouse  *objectbox.PropertyBool
}{
	Id: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &AppUserBinding.Entity,
		},
	},
	ExtId: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &AppUserBinding.Entity,
		},
	},
	CreatedAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &AppUserBinding.Entity,
		},
	},
	UpdatedAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     6,
			Entity: &AppUserBinding.Entity,
		},
	},
	FirstName: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     7,
			Entity: &AppUserBinding.Entity,
		},
	},
	LastName: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     8,
			Entity: &AppUserBinding.Entity,
		},
	},
	Email: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     9,
			Entity: &AppUserBinding.Entity,
		},
	},
	Phone: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     10,
			Entity: &AppUserBinding.Entity,
		},
	},
	Token: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     11,
			Entity: &AppUserBinding.Entity,
		},
	},
	IsBlocked: &objectbox.PropertyBool{
		BaseProperty: &objectbox.BaseProperty{
			Id:     12,
			Entity: &AppUserBinding.Entity,
		},
	},
	IsFarm: &objectbox.PropertyBool{
		BaseProperty: &objectbox.BaseProperty{
			Id:     13,
			Entity: &AppUserBinding.Entity,
		},
	},
	IsGasStation: &objectbox.PropertyBool{
		BaseProperty: &objectbox.BaseProperty{
			Id:     14,
			Entity: &AppUserBinding.Entity,
		},
	},
	IsHarvesting: &objectbox.PropertyBool{
		BaseProperty: &objectbox.BaseProperty{
			Id:     15,
			Entity: &AppUserBinding.Entity,
		},
	},
	IsPayDesk: &objectbox.PropertyBool{
		BaseProperty: &objectbox.BaseProperty{
			Id:     16,
			Entity: &AppUserBinding.Entity,
		},
	},
	IsWarehouse: &objectbox.PropertyBool{
		BaseProperty: &objectbox.BaseProperty{
			Id:     17,
			Entity: &AppUserBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (appUser_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (appUser_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("AppUser", 2, 3772536781229214116)
	model.Property("Id", 6, 1, 1727067599752868172)
	model.PropertyFlags(1)
	model.Property("ExtId", 9, 2, 1751440294866873485)
	model.Property("CreatedAt", 10, 5, 2560859963279789654)
	model.Property("UpdatedAt", 10, 6, 6879137370614292715)
	model.Property("FirstName", 9, 7, 5371987638100000232)
	model.Property("LastName", 9, 8, 7064546187212738440)
	model.Property("Email", 9, 9, 4256892128440117593)
	model.Property("Phone", 9, 10, 8766869086574508498)
	model.Property("Token", 9, 11, 6198435271220425000)
	model.Property("IsBlocked", 1, 12, 5936673092836650890)
	model.Property("IsFarm", 1, 13, 6391471651868091211)
	model.Property("IsGasStation", 1, 14, 8380961054502993825)
	model.Property("IsHarvesting", 1, 15, 5881266140801353583)
	model.Property("IsPayDesk", 1, 16, 6970975710831344500)
	model.Property("IsWarehouse", 1, 17, 6958713036560849743)
	model.EntityLastPropertyId(17, 6958713036560849743)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (appUser_EntityInfo) GetId(object interface{}) (uint64, error) {
	return uint64(object.(*AppUser).Id), nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (appUser_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*AppUser).Id = int64(id)
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (appUser_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (appUser_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*AppUser)
	var propCreatedAt int64
	{
		var err error
		propCreatedAt, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.CreatedAt)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on AppUser.CreatedAt: " + err.Error())
		}
	}

	var propUpdatedAt int64
	{
		var err error
		propUpdatedAt, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.UpdatedAt)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on AppUser.UpdatedAt: " + err.Error())
		}
	}

	var offsetExtId = fbutils.CreateStringOffset(fbb, obj.ExtId)
	var offsetFirstName = fbutils.CreateStringOffset(fbb, obj.FirstName)
	var offsetLastName = fbutils.CreateStringOffset(fbb, obj.LastName)
	var offsetEmail = fbutils.CreateStringOffset(fbb, obj.Email)
	var offsetPhone = fbutils.CreateStringOffset(fbb, obj.Phone)
	var offsetToken = fbutils.CreateStringOffset(fbb, obj.Token)

	// build the FlatBuffers object
	fbb.StartObject(17)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetExtId)
	fbutils.SetUOffsetTSlot(fbb, 6, offsetFirstName)
	fbutils.SetUOffsetTSlot(fbb, 7, offsetLastName)
	fbutils.SetUOffsetTSlot(fbb, 8, offsetEmail)
	fbutils.SetUOffsetTSlot(fbb, 9, offsetPhone)
	fbutils.SetUOffsetTSlot(fbb, 10, offsetToken)
	fbutils.SetBoolSlot(fbb, 11, obj.IsBlocked)
	fbutils.SetBoolSlot(fbb, 12, obj.IsFarm)
	fbutils.SetBoolSlot(fbb, 13, obj.IsGasStation)
	fbutils.SetBoolSlot(fbb, 14, obj.IsHarvesting)
	fbutils.SetBoolSlot(fbb, 15, obj.IsPayDesk)
	fbutils.SetBoolSlot(fbb, 16, obj.IsWarehouse)
	fbutils.SetInt64Slot(fbb, 4, propCreatedAt)
	fbutils.SetInt64Slot(fbb, 5, propUpdatedAt)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (appUser_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'AppUser' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetInt64Slot(4, 0)

	propCreatedAt, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 12))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on AppUser.CreatedAt: " + err.Error())
	}

	propUpdatedAt, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 14))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on AppUser.UpdatedAt: " + err.Error())
	}

	return &AppUser{
		Id:           propId,
		ExtId:        fbutils.GetStringSlot(table, 6),
		FirstName:    fbutils.GetStringSlot(table, 16),
		LastName:     fbutils.GetStringSlot(table, 18),
		Email:        fbutils.GetStringSlot(table, 20),
		Phone:        fbutils.GetStringSlot(table, 22),
		Token:        fbutils.GetStringSlot(table, 24),
		IsBlocked:    fbutils.GetBoolSlot(table, 26),
		IsFarm:       fbutils.GetBoolSlot(table, 28),
		IsGasStation: fbutils.GetBoolSlot(table, 30),
		IsHarvesting: fbutils.GetBoolSlot(table, 32),
		IsPayDesk:    fbutils.GetBoolSlot(table, 34),
		IsWarehouse:  fbutils.GetBoolSlot(table, 36),
		CreatedAt:    propCreatedAt,
		UpdatedAt:    propUpdatedAt,
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (appUser_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*AppUser, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (appUser_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*AppUser), nil)
	}
	return append(slice.([]*AppUser), object.(*AppUser))
}

// Box provides CRUD access to AppUser objects
type AppUserBox struct {
	*objectbox.Box
}

// BoxForAppUser opens a box of AppUser objects
func BoxForAppUser(ob *objectbox.ObjectBox) *AppUserBox {
	return &AppUserBox{
		Box: ob.InternalBox(2),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the AppUser.Id property on the passed object will be assigned the new ID as well.
func (box *AppUserBox) Put(object *AppUser) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the AppUser.Id property on the passed object will be assigned the new ID as well.
func (box *AppUserBox) Insert(object *AppUser) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *AppUserBox) Update(object *AppUser) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *AppUserBox) PutAsync(object *AppUser) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the AppUser.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the AppUser.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *AppUserBox) PutMany(objects []*AppUser) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *AppUserBox) Get(id uint64) (*AppUser, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*AppUser), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *AppUserBox) GetMany(ids ...uint64) ([]*AppUser, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*AppUser), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *AppUserBox) GetManyExisting(ids ...uint64) ([]*AppUser, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*AppUser), nil
}

// GetAll reads all stored objects
func (box *AppUserBox) GetAll() ([]*AppUser, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*AppUser), nil
}

// Remove deletes a single object
func (box *AppUserBox) Remove(object *AppUser) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *AppUserBox) RemoveMany(objects ...*AppUser) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = uint64(object.Id)
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the AppUser_ struct to create conditions.
// Keep the *AppUserQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *AppUserBox) Query(conditions ...objectbox.Condition) *AppUserQuery {
	return &AppUserQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the AppUser_ struct to create conditions.
// Keep the *AppUserQuery if you intend to execute the query multiple times.
func (box *AppUserBox) QueryOrError(conditions ...objectbox.Condition) (*AppUserQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &AppUserQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See AppUserAsyncBox for more information.
func (box *AppUserBox) Async() *AppUserAsyncBox {
	return &AppUserAsyncBox{AsyncBox: box.Box.Async()}
}

// AppUserAsyncBox provides asynchronous operations on AppUser objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type AppUserAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForAppUser creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use AppUserBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForAppUser(ob *objectbox.ObjectBox, timeoutMs uint64) *AppUserAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 2, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 2: %s" + err.Error())
	}
	return &AppUserAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *AppUserAsyncBox) Put(object *AppUser) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *AppUserAsyncBox) Insert(object *AppUser) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *AppUserAsyncBox) Update(object *AppUser) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *AppUserAsyncBox) Remove(object *AppUser) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all AppUser which Id is either 42 or 47:
// 		box.Query(AppUser_.Id.In(42, 47)).Find()
type AppUserQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *AppUserQuery) Find() ([]*AppUser, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*AppUser), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *AppUserQuery) Offset(offset uint64) *AppUserQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *AppUserQuery) Limit(limit uint64) *AppUserQuery {
	query.Query.Limit(limit)
	return query
}
