// Code generated by ObjectBox; DO NOT EDIT.

package models

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

// ObjectBoxModel declares and builds the model from all the entities in the package.
// It is usually used when setting-up ObjectBox as an argument to the Builder.Model() function.
func ObjectBoxModel() *objectbox.Model {
	model := objectbox.NewModel()
	model.GeneratorVersion(6)

	model.RegisterBinding(PersonBinding)
	model.RegisterBinding(AppUserBinding)
	model.RegisterBinding(ConsignmentNoteInBinding)
	model.RegisterBinding(GoodsConsignmentNoteInBinding)
	model.RegisterBinding(GoodsBinding)
	model.RegisterBinding(GoodsGroupBinding)
	model.RegisterBinding(HarvestTypeBinding)
	model.RegisterBinding(StorageBinding)
	model.RegisterBinding(SubdivisionBinding)
	model.RegisterBinding(UnitBinding)
	model.RegisterBinding(VehicleBinding)	
	model.LastEntityId(12, 934482826225446963)
	model.LastIndexId(39, 7088705508277379986)
	model.LastRelationId(2, 1629334969059597573)

	return model
}
