// Code generated by ObjectBox; DO NOT EDIT.
// Learn more about defining entities and generating this file - visit https://golang.objectbox.io/entity-annotations

package models

import (
	"errors"
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type serviceWorker_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var ServiceWorkerBinding = serviceWorker_EntityInfo{
	Entity: objectbox.Entity{
		Id: 16,
	},
	Uid: 602108393020751439,
}

// ServiceWorker_ contains type-based Property helpers to facilitate some common operations such as Queries.
var ServiceWorker_ = struct {
	Id        *objectbox.PropertyUint64
	ExtId     *objectbox.PropertyString
	Name      *objectbox.PropertyString
	NfcId     *objectbox.PropertyString
	IsDeleted *objectbox.PropertyBool
	CreatedAt *objectbox.PropertyInt64
	UpdatedAt *objectbox.PropertyInt64
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &ServiceWorkerBinding.Entity,
		},
	},
	ExtId: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &ServiceWorkerBinding.Entity,
		},
	},
	Name: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &ServiceWorkerBinding.Entity,
		},
	},
	NfcId: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &ServiceWorkerBinding.Entity,
		},
	},
	IsDeleted: &objectbox.PropertyBool{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &ServiceWorkerBinding.Entity,
		},
	},
	CreatedAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     6,
			Entity: &ServiceWorkerBinding.Entity,
		},
	},
	UpdatedAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     7,
			Entity: &ServiceWorkerBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (serviceWorker_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (serviceWorker_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("ServiceWorker", 16, 602108393020751439)
	model.Property("Id", 6, 1, 7331691873490605167)
	model.PropertyFlags(1)
	model.Property("ExtId", 9, 2, 7695352268246587039)
	model.Property("Name", 9, 3, 1893548107152200160)
	model.Property("NfcId", 9, 4, 3884436839836727570)
	model.Property("IsDeleted", 1, 5, 4815040914526060082)
	model.Property("CreatedAt", 10, 6, 7730011172501733841)
	model.Property("UpdatedAt", 10, 7, 5773654480249983142)
	model.EntityLastPropertyId(7, 5773654480249983142)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (serviceWorker_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*ServiceWorker).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (serviceWorker_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*ServiceWorker).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (serviceWorker_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (serviceWorker_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*ServiceWorker)
	var propCreatedAt int64
	{
		var err error
		propCreatedAt, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.CreatedAt)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on ServiceWorker.CreatedAt: " + err.Error())
		}
	}

	var propUpdatedAt int64
	{
		var err error
		propUpdatedAt, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.UpdatedAt)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on ServiceWorker.UpdatedAt: " + err.Error())
		}
	}

	var offsetExtId = fbutils.CreateStringOffset(fbb, obj.ExtId)
	var offsetName = fbutils.CreateStringOffset(fbb, obj.Name)
	var offsetNfcId = fbutils.CreateStringOffset(fbb, obj.NfcId)

	// build the FlatBuffers object
	fbb.StartObject(7)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetExtId)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetName)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetNfcId)
	fbutils.SetBoolSlot(fbb, 4, obj.IsDeleted)
	fbutils.SetInt64Slot(fbb, 5, propCreatedAt)
	fbutils.SetInt64Slot(fbb, 6, propUpdatedAt)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (serviceWorker_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'ServiceWorker' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	propCreatedAt, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 14))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on ServiceWorker.CreatedAt: " + err.Error())
	}

	propUpdatedAt, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 16))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on ServiceWorker.UpdatedAt: " + err.Error())
	}

	return &ServiceWorker{
		Id:        propId,
		ExtId:     fbutils.GetStringSlot(table, 6),
		Name:      fbutils.GetStringSlot(table, 8),
		NfcId:     fbutils.GetStringSlot(table, 10),
		IsDeleted: fbutils.GetBoolSlot(table, 12),
		CreatedAt: propCreatedAt,
		UpdatedAt: propUpdatedAt,
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (serviceWorker_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*ServiceWorker, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (serviceWorker_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*ServiceWorker), nil)
	}
	return append(slice.([]*ServiceWorker), object.(*ServiceWorker))
}

// Box provides CRUD access to ServiceWorker objects
type ServiceWorkerBox struct {
	*objectbox.Box
}

// BoxForServiceWorker opens a box of ServiceWorker objects
func BoxForServiceWorker(ob *objectbox.ObjectBox) *ServiceWorkerBox {
	return &ServiceWorkerBox{
		Box: ob.InternalBox(16),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the ServiceWorker.Id property on the passed object will be assigned the new ID as well.
func (box *ServiceWorkerBox) Put(object *ServiceWorker) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the ServiceWorker.Id property on the passed object will be assigned the new ID as well.
func (box *ServiceWorkerBox) Insert(object *ServiceWorker) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *ServiceWorkerBox) Update(object *ServiceWorker) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *ServiceWorkerBox) PutAsync(object *ServiceWorker) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the ServiceWorker.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the ServiceWorker.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *ServiceWorkerBox) PutMany(objects []*ServiceWorker) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *ServiceWorkerBox) Get(id uint64) (*ServiceWorker, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*ServiceWorker), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *ServiceWorkerBox) GetMany(ids ...uint64) ([]*ServiceWorker, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*ServiceWorker), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *ServiceWorkerBox) GetManyExisting(ids ...uint64) ([]*ServiceWorker, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*ServiceWorker), nil
}

// GetAll reads all stored objects
func (box *ServiceWorkerBox) GetAll() ([]*ServiceWorker, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*ServiceWorker), nil
}

// Remove deletes a single object
func (box *ServiceWorkerBox) Remove(object *ServiceWorker) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *ServiceWorkerBox) RemoveMany(objects ...*ServiceWorker) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the ServiceWorker_ struct to create conditions.
// Keep the *ServiceWorkerQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *ServiceWorkerBox) Query(conditions ...objectbox.Condition) *ServiceWorkerQuery {
	return &ServiceWorkerQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the ServiceWorker_ struct to create conditions.
// Keep the *ServiceWorkerQuery if you intend to execute the query multiple times.
func (box *ServiceWorkerBox) QueryOrError(conditions ...objectbox.Condition) (*ServiceWorkerQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &ServiceWorkerQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See ServiceWorkerAsyncBox for more information.
func (box *ServiceWorkerBox) Async() *ServiceWorkerAsyncBox {
	return &ServiceWorkerAsyncBox{AsyncBox: box.Box.Async()}
}

// ServiceWorkerAsyncBox provides asynchronous operations on ServiceWorker objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type ServiceWorkerAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForServiceWorker creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use ServiceWorkerBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForServiceWorker(ob *objectbox.ObjectBox, timeoutMs uint64) *ServiceWorkerAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 16, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 16: %s" + err.Error())
	}
	return &ServiceWorkerAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *ServiceWorkerAsyncBox) Put(object *ServiceWorker) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *ServiceWorkerAsyncBox) Insert(object *ServiceWorker) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *ServiceWorkerAsyncBox) Update(object *ServiceWorker) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *ServiceWorkerAsyncBox) Remove(object *ServiceWorker) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all ServiceWorker which Id is either 42 or 47:
// 		box.Query(ServiceWorker_.Id.In(42, 47)).Find()
type ServiceWorkerQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *ServiceWorkerQuery) Find() ([]*ServiceWorker, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*ServiceWorker), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *ServiceWorkerQuery) Offset(offset uint64) *ServiceWorkerQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *ServiceWorkerQuery) Limit(limit uint64) *ServiceWorkerQuery {
	query.Query.Limit(limit)
	return query
}
